/**
 * Compact Compiler Output: SealBidContract
 * Auto-generated by compactc compiler for Midnight Network
 */

export const SEALBID_CIRCUITS_METADATA = {
  contractName: "SealBidContract",
  version: "1.0.0",
  targetNetwork: "preview",
  circuits: [
    {
      name: "submit_sealed_bid",
      description: "Proves bid_amount >= reserve_price without revealing bid_amount",
      inputsCount: 2,
      witnessCount: 3,
      provingKeyHash: "0xa8f3b2c9d1e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8",
      verificationKeyHash: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    },
    {
      name: "reveal_bid",
      description: "Proves commitment matches revealed_amount and salt post-deadline",
      inputsCount: 3,
      witnessCount: 2,
      provingKeyHash: "0xb9e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2",
      verificationKeyHash: "0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c",
    },
    {
      name: "settle_auction",
      description: "Verifies settlement conditions and transitions state",
      inputsCount: 1,
      witnessCount: 0,
      provingKeyHash: "0xc0f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3",
      verificationKeyHash: "0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
    },
  ],
};

export const CONTRACT_BYTECODE_HASH =
  "0x98f4e2a1b3c5d7e9f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6";
